#!/usr/bin/env python3
"""Generate a scenario coverage index from explicit records in result reports."""

import argparse
from datetime import date
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parent.parent
BLOCK = re.compile(r'^```scenario-results\n(.*?)^```[ \t]*$', re.M | re.S)
FIELDS = {'scenario', 'date', 'skill_commit', 'runner', 'model', 'grade', 'phase', 'note', 'order'}


class RecordError(ValueError):
    pass


def records(root):
    scenarios = {p.stem for p in (root / 'evals/scenarios').glob('*.md')}
    found = {name: [] for name in scenarios}
    for path in sorted((root / 'evals/results').glob('*.md')):
        text = path.read_text(encoding='utf-8')
        blocks = BLOCK.findall(text)
        if text.count('```scenario-results') != len(blocks) or not blocks:
            raise RecordError(f'{path.name}: missing or malformed scenario-results block')
        for block in blocks:
            try:
                rows = json.loads(block)
            except json.JSONDecodeError as error:
                raise RecordError(f'{path.name}: invalid JSON: {error}') from error
            if not isinstance(rows, list) or not rows:
                raise RecordError(f'{path.name}: expected a nonempty record list')
            for row in rows:
                if not isinstance(row, dict) or set(row) != FIELDS:
                    raise RecordError(f'{path.name}: records require fields {", ".join(sorted(FIELDS))}')
                if any(value is not None and (not isinstance(value, str) or not value.strip())
                       for key, value in row.items() if key != 'order'):
                    raise RecordError(f'{path.name}: values must be nonempty strings or null')
                if row['order'] is not None and (type(row['order']) is not int or row['order'] < 1):
                    raise RecordError(f'{path.name}: order must be a positive integer or null')
                name = row['scenario']
                if name not in scenarios:
                    raise RecordError(f'{path.name}: unknown scenario {name!r}')
                if row['date'] is not None:
                    try:
                        parsed = date.fromisoformat(row['date'])
                        if parsed.isoformat() != row['date']:
                            raise ValueError()
                    except ValueError as error:
                        raise RecordError(f'{path.name}: invalid date {row["date"]!r}') from error
                found[name].append((path.name, row))
    return found


def cell(value):
    return 'unknown' if value is None else value.replace('\\', '\\\\').replace('|', '\\|').replace('\n', '<br>').replace('\r', '')


def render(root=None):
    root = ROOT if root is None else root
    found = records(root)
    lines = ['# Scenario coverage index', '',
             'Generated by `python3 scripts/scenario_index.py`. Do not edit this file by hand.', '',
             'Dates and metadata come from the linked reports. Unknown means that the report supplies no supported value.',
             'Records on the latest known date appear together, except earlier ordered phases within one report. Undated records also appear.',
             'A different repository HEAD does not invalidate a recorded run. Read the report to assess source and criteria changes.', '',
             '## Recorded runs', '',
             '| Scenario | Date | Skill commit | Runner | Selected or recorded model | Grade | Phase | Report and limits |',
             '| --- | --- | --- | --- | --- | --- | --- | --- |']
    for name, entries in sorted(found.items()):
        if not entries:
            continue
        latest = max((row['date'] for _, row in entries if row['date']), default=None)
        selected = [(report, row) for report, row in entries if row['date'] is None or row['date'] == latest]
        # Ordering is local to a report and scenario; it never compares two reports.
        selected = [(report, row) for report, row in selected
                    if row['order'] is None or not any(
                        other_report == report and other['order'] is not None
                        and other['order'] > row['order']
                        for other_report, other in selected)]
        selected.sort(key=lambda item: (item[0], json.dumps(item[1], sort_keys=True)))
        for report, row in selected:
            values = [f'[{name}](scenarios/{name}.md)']
            values.extend(cell(row[field]) for field in ('date', 'skill_commit', 'runner', 'model', 'grade', 'phase'))
            values.append(f'[{report}](results/{report})' + (f': {cell(row["note"])}' if row['note'] else ''))
            lines.append('| ' + ' | '.join(values) + ' |')
    lines.extend(['', '## No recorded run', '',
                  'These scenarios have no structured run record in the reports. This does not prove that no unrecorded run occurred.', ''])
    lines.extend(f'- [{name}](scenarios/{name}.md)' for name, entries in sorted(found.items()) if not entries)
    return '\n'.join(lines) + '\n'


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='fail if the committed index differs from generated content')
    args = parser.parse_args(argv)
    try:
        content = render()
        path = ROOT / 'evals/INDEX.md'
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8') != content:
                raise RecordError('evals/INDEX.md is stale; run python3 scripts/scenario_index.py')
        else:
            path.write_text(content, encoding='utf-8')
    except (RecordError, OSError) as error:
        print(f'scenario_index: {error}', file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
